package com.tullyo.wallet.infrastructure.adapters.inbound.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.RequiredArgsConstructor;

@Data
@RequiredArgsConstructor
@DynamoDBTable(tableName = "Carteira")
public class WalletEntity {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute
  private String title;

  @DynamoDBAttribute
  private String name;

  @DynamoDBAttribute
  private String segment;

  @DynamoDBAttribute
  private String type;

}
