package com.tullyo.buying.of.securities.infrastructure.adapters.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.tullyo.buying.of.securities.domain.converters.AmountConverter;
import com.tullyo.buying.of.securities.domain.converters.LocalDateTimeConverter;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@RequiredArgsConstructor
@DynamoDBTable(tableName = "CompraTitulo")
public class TitlePurchaseEntity {

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String id;

  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
  private LocalDateTime monthOfPurchase;

  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = AmountConverter.class)
  private BigDecimal amountPaid;

  @DynamoDBTypeConverted(converter = AmountConverter.class)
  private BigDecimal dividendValue;

  @DynamoDBAttribute
  private Integer quantity;

  @DynamoDBAttribute
  private WalletEntity wallet;

}
